[MOD] Changed option parsing from manual to getopts (zsh-builtin)

diff --git a/zgit-repo-user-config b/zgit-repo-user-config
--- a/zgit-repo-user-config
+++ b/zgit-repo-user-config
@@ -1,57 +1,60 @@
 function zgit-repo-user-config-main()
 {
     # If option -a is given, configure as new path
-    local given_option
     local user_name user_mail
     local stored_path
 
-    given_option="$(echo $1 | xargs | cut -d ' ' -f 1)"
+    # Hooks -a option
+    while getopts :a opt; do
+        case ${opt} in
+            a)
+                [[ -n "${ZGITREPO_USER_CONFIG_FILE}" ]] && {
+                    [[ ! -e $ZGITREPO_USER_CONFIG_FILE ]] && {
+                        touch $ZGITREPO_USER_CONFIG_FILE
+                        echo "[INFO] Initialized ${ZGITREPO_USER_CONFIG_FILE}"
+                    }
 
-    [[ "${given_option}" == '-a' ]] && {
-        [[ -n "${ZGITREPO_USER_CONFIG_FILE}" ]] && {
-            [[ ! -e $ZGITREPO_USER_CONFIG_FILE ]] && {
-                touch $ZGITREPO_USER_CONFIG_FILE
-                echo "[INFO] Initialized ${ZGITREPO_USER_CONFIG_FILE}"
-            }
+                    # Check path included or not
+                    foreach stored_path ($(cat $ZGITREPO_USER_CONFIG_FILE | cut -d '%' -f 1)); do
+                        [[ "$(pwd)" =~ "^${stored_path}.*$" ]] && {
+                            echo "[ERROR] Registered path ${stored_path} includes current directory" 1>&2
+                            return -1
+                        }
 
-            # Check path included or not
-            foreach stored_path ($(cat $ZGITREPO_USER_CONFIG_FILE | cut -d '%' -f 1)); do
-                [[ "$(pwd)" =~ "^${stored_path}.*$" ]] && {
-                    echo "[ERROR] Registered path ${stored_path} includes current directory" 1>&2
+                        [[ "${stored_path}" =~ "^$(pwd).*$" ]] && {
+                            echo "[ERROR] Child path ${stored_path} is already registered" 1>&2
+                            return -1
+                        }
+                    ; done
+
+                    # Put user information
+                    vared -p 'Your name  >> ' -c user_name
+                    vared -p 'Your email >> ' -c user_mail
+
+                    [[ -z "${user_name}" || -z "${user_mail}" ]] && {
+                        echo "[ERROR] Username and mail address must be specified" 1>&2
+                        return -1
+                    }
+
+                    # Write record
+                    echo "$(pwd)%${user_name}%${user_mail}" >> $ZGITREPO_USER_CONFIG_FILE
+
+                    # Show information
+                    echo "Configured as"
+                    echo "    Path:  $(pwd)"
+                    echo "    Name:  ${user_name}"
+                    echo "    Email: ${user_mail}"
+
+                    return 0
+
+                } || {
+                    echo "[ERROR] Variable ZGITREPO_USER_CONFIG_FILE not configured" 1>&2
                     return -1
                 }
+                ;;
+        esac
+    ; done
 
-                [[ "${stored_path}" =~ "^$(pwd).*$" ]] && {
-                    echo "[ERROR] Child path ${stored_path} is already registered" 1>&2
-                    return -1
-                }
-            ; done
-
-            # Put user information
-            vared -p 'Your name  >> ' -c user_name
-            vared -p 'Your email >> ' -c user_mail
-
-            [[ -z "${user_name}" || -z "${user_mail}" ]] && {
-                echo "[ERROR] Username and mail address must be specified" 1>&2
-                return -1
-            }
-
-            # Write record
-            echo "$(pwd)%${user_name}%${user_mail}" >> $ZGITREPO_USER_CONFIG_FILE
-
-            # Show information
-            echo "Configured as"
-            echo "    Path:  $(pwd)"
-            echo "    Name:  ${user_name}"
-            echo "    Email: ${user_mail}"
-
-            return 0
-
-        } || {
-            echo "[ERROR] Variable ZGITREPO_USER_CONFIG_FILE not configured" 1>&2
-            return -1
-        }
-    }
 
     # Check current directory is under git repo or not
     [[ ! -n "$(git branch 2>/dev/null)" ]] && {
